apiVersion: v1
kind: ServiceAccount
metadata:
  name: index-01-hook
  namespace: index-01-hook
  labels:
    app.kubernetes.io/name: index-01-hook
    app.kubernetes.io/part-of: index-01
automountServiceAccountToken: false
